# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RNP.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(672, 301)
        Main.setMinimumSize(QtCore.QSize(672, 301))
        Main.setMaximumSize(QtCore.QSize(672, 301))
        Main.setStyleSheet("background:  rgb(55,72,130)")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Main)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.face_frame = QtWidgets.QFrame(Main)
        self.face_frame.setStyleSheet("QFrame:hover{\n"
"border: 5px solid rgb(26,169,253);\n"
"background:rgb(110,120,148);\n"
"border-radius: 15px;\n"
"}")
        self.face_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.face_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.face_frame.setObjectName("face_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.face_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bt_face = QtWidgets.QPushButton(self.face_frame)
        self.bt_face.setMinimumSize(QtCore.QSize(200, 250))
        self.bt_face.setMaximumSize(QtCore.QSize(200, 250))
        self.bt_face.setTabletTracking(False)
        self.bt_face.setAcceptDrops(False)
        self.bt_face.setAutoFillBackground(False)
        self.bt_face.setStyleSheet("")
        self.bt_face.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo/face.jpg"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.bt_face.setIcon(icon)
        self.bt_face.setIconSize(QtCore.QSize(230, 250))
        self.bt_face.setAutoRepeat(False)
        self.bt_face.setAutoDefault(False)
        self.bt_face.setDefault(False)
        self.bt_face.setFlat(False)
        self.bt_face.setObjectName("bt_face")
        self.bt_face.clicked.connect(self.startFaceRecognition)
        self.verticalLayout.addWidget(self.bt_face)
        self.text_face = QtWidgets.QLabel(self.face_frame)
        self.text_face.setMinimumSize(QtCore.QSize(0, 25))
        self.text_face.setMaximumSize(QtCore.QSize(16777215, 25))
        self.text_face.setStyleSheet("border: opx;\n"
"background: transparent;\n"
"color: white;")
        self.text_face.setTextFormat(QtCore.Qt.AutoText)
        self.text_face.setAlignment(QtCore.Qt.AlignCenter)
        self.text_face.setObjectName("text_face")
        self.verticalLayout.addWidget(self.text_face)
        self.horizontalLayout.addWidget(self.face_frame)
        self.posture_frame = QtWidgets.QFrame(Main)
        self.posture_frame.setStyleSheet("QFrame:hover{\n"
"border: 5px solid rgb(26,169,253);\n"
"background:rgb(110,120,148);\n"
"border-radius: 15px;\n"
"}")
        self.posture_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.posture_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.posture_frame.setObjectName("posture_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.posture_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.bt_posture = QtWidgets.QPushButton(self.posture_frame)
        self.bt_posture.setMinimumSize(QtCore.QSize(200, 250))
        self.bt_posture.setMaximumSize(QtCore.QSize(200, 250))
        self.bt_posture.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("logo/posture.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_posture.setIcon(icon1)
        self.bt_posture.setIconSize(QtCore.QSize(250, 260))
        self.bt_posture.setObjectName("bt_posture")
        self.bt_posture.clicked.connect(self.startPostureRecognition)
        self.verticalLayout_2.addWidget(self.bt_posture)
        self.text_posture = QtWidgets.QLabel(self.posture_frame)
        self.text_posture.setMinimumSize(QtCore.QSize(0, 25))
        self.text_posture.setMaximumSize(QtCore.QSize(16777215, 25))
        self.text_posture.setStyleSheet("border: opx;\n"
"background: transparent;\n"
"color: white;")
        self.text_posture.setAlignment(QtCore.Qt.AlignCenter)
        self.text_posture.setObjectName("text_posture")
        self.verticalLayout_2.addWidget(self.text_posture)
        self.horizontalLayout.addWidget(self.posture_frame)
        self.age_gen_frame = QtWidgets.QFrame(Main)
        self.age_gen_frame.setStyleSheet("QFrame:hover{\n"
"border: 5px solid rgb(26,169,253);\n"
"background:rgb(110,120,148);\n"
"border-radius: 15px;\n"
"}")
        self.age_gen_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.age_gen_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.age_gen_frame.setObjectName("age_gen_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.age_gen_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.bt_age_gen = QtWidgets.QPushButton(self.age_gen_frame)
        self.bt_age_gen.setMinimumSize(QtCore.QSize(200, 250))
        self.bt_age_gen.setMaximumSize(QtCore.QSize(200, 250))
        self.bt_age_gen.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("logo/age.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_age_gen.setIcon(icon2)
        self.bt_age_gen.setIconSize(QtCore.QSize(280, 280))
        self.bt_age_gen.setObjectName("bt_age_gen")
        self.bt_age_gen.clicked.connect(self.startAgeGenRecognition)
        self.verticalLayout_3.addWidget(self.bt_age_gen)
        self.text_age_display = QtWidgets.QLabel(self.age_gen_frame)
        self.text_age_display.setMinimumSize(QtCore.QSize(0, 25))
        self.text_age_display.setMaximumSize(QtCore.QSize(16777215, 25))
        self.text_age_display.setStyleSheet("border: opx;\n"
"background: transparent;\n"
"color: white;")
        self.text_age_display.setAlignment(QtCore.Qt.AlignCenter)
        self.text_age_display.setObjectName("text_age_display")
        self.verticalLayout_3.addWidget(self.text_age_display)
        self.horizontalLayout.addWidget(self.age_gen_frame)

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Multimodal Biometric Identification"))
        self.text_face.setText(_translate("Main", "Facial Recognition"))
        self.text_posture.setText(_translate("Main", "Posture Recognition"))
        self.text_age_display.setText(_translate("Main", "Age / Gen Recognition"))

    def startFaceRecognition(self):
        from database_view import Ui_databaseView
        self.windows = QtWidgets.QWidget()
        self.ui = Ui_databaseView()
        self.ui.setupUi(self.windows)
        self.windows.show()

    def startPostureRecognition(self):
        exec(open('posture.py').read())

    def startAgeGenRecognition(self):
        from gender_view import Ui_databaseView
        self.windows = QtWidgets.QWidget()
        self.ui = Ui_databaseView()
        self.ui.setupUi(self.windows)
        self.windows.show()
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Main = QtWidgets.QWidget()
    ui = Ui_Main()
    ui.setupUi(Main)
    Main.show()
    sys.exit(app.exec_())
